/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is JSwat Installer. The Initial Developer of the
 * Software is Nathan L. Fiedler. Portions created by Nathan L. Fiedler
 * are Copyright (C) 2005-2009. All Rights Reserved.
 *
 * Contributor(s): Nathan L. Fiedler.
 *
 * $Id$
 */

package com.bluemarsh.jswat.installer;

import java.io.File;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 * Displays the summary screen of the installer.
 *
 * @author  Nathan Fiedler
 */
public class SummaryPanel extends InstallerPanel {
    /** silence compiler warnings */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form SummaryPanel.
     */
    public SummaryPanel() {
        initComponents();

        // Set up the text pane styles.
        StyledDocument doc = reviewTextPane.getStyledDocument();
        addStylesToDocument(doc);
    }

    /**
     * Set up the styles for the styled document.
     *
     * @param  doc  styled document to prepare.
     */
    private void addStylesToDocument(StyledDocument doc) {
        Style def = StyleContext.getDefaultStyleContext().getStyle(
                StyleContext.DEFAULT_STYLE);

        Style regular = doc.addStyle("regular", def);
        StyleConstants.setFontFamily(def, "SansSerif");

        Style s = doc.addStyle("emphasized", regular);
        StyleConstants.setBold(s, true);
    }

    @Override
    public void doHide() {
    }

    @Override
    public void doShow() {
        Controller.getDefault().markCompleted();
        populateText();
    }

    @Override
    public String getNext() {
        return null;
    }

    @Override
    public String getPrevious() {
        return null;
    }

    /**
     * Populate the text pane with the latest information.
     */
    private void populateText() {
        StyledDocument doc = reviewTextPane.getStyledDocument();
        try {
            Style rstyle = doc.getStyle("regular");
            Style estyle = doc.getStyle("emphasized");
            String msg = Bundle.getString("MSG_Summary_Message");
            doc.insertString(doc.getLength(), msg, rstyle);
            msg = Bundle.getString("MSG_Summary_Location");
            doc.insertString(doc.getLength(), msg, rstyle);
            String home = Controller.getDefault().getProperty("home");
            doc.insertString(doc.getLength(), home, rstyle);
            msg = Bundle.getString("MSG_Summary_Executable");
            doc.insertString(doc.getLength(), msg, estyle);
            String exec = home + File.separator + "bin" + File.separator + "jswat";
            doc.insertString(doc.getLength(), exec, rstyle);
        } catch (BadLocationException ble) {
            // This would be entirely unexpected.
            ble.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        reviewTextPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        reviewTextPane.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        reviewTextPane.setEditable(false);
        reviewTextPane.setFocusable(false);
        reviewTextPane.setMargin(new java.awt.Insets(12, 12, 12, 12));
        add(reviewTextPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane reviewTextPane;
    // End of variables declaration//GEN-END:variables
}
