/*
 *                     Sun Public License Notice.
 *
 * The contents of this file are subject to the Sun Public License 
 * Version 1.0 (the "License"); you may not use this file except in 
 * compliance with the License. A copy of the License is available at 
 * http://www.sun.com/
 *
 * The Original Code is JSwat Installer. The Initial Developer of the 
 * Original Code is Nathan L. Fiedler. Portions created by Nathan L. Fiedler
 * are Copyright (C) 2005. All Rights Reserved.
 *
 * Contributor(s): Nathan L. Fiedler.
 *
 * $Id: WelcomePanel.java 15 2007-06-03 00:01:17Z nfiedler $
 */

package com.bluemarsh.jswat.installer;

import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 * Displays the welcome screen of the installer.
 *
 * @author  Nathan Fiedler
 */
public class WelcomePanel extends InstallerPanel {
    /** silence compiler warnings */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form WelcomePanel.
     */
    public WelcomePanel() {
        initComponents();

        // Set up the text pane styles.
        StyledDocument doc = welcomeTextPane.getStyledDocument();
        addStylesToDocument(doc);

        // Populate the text pane with styled text.
        try {
            String msg = Bundle.getString("MSG_Welcome_Title");
            doc.insertString(doc.getLength(), msg, doc.getStyle("large"));
            msg = Bundle.getString("MSG_Welcome_Body");
            doc.insertString(doc.getLength(), msg, doc.getStyle("regular"));
        } catch (BadLocationException ble) {
            // This would be entirely unexpected.
            ble.printStackTrace();
        }
    }

    /**
     * Set up the styles for the styled document.
     *
     * @param  doc  styled document to prepare.
     */
    private void addStylesToDocument(StyledDocument doc) {
        Style def = StyleContext.getDefaultStyleContext().getStyle(
                StyleContext.DEFAULT_STYLE);

        Style regular = doc.addStyle("regular", def);
        StyleConstants.setFontFamily(def, "SansSerif");

        Style s = doc.addStyle("large", regular);
        StyleConstants.setBold(s, true);
        StyleConstants.setFontSize(s, 16);
    }

    public void doHide() {
    }

    public void doShow() {
    }

    public String getNext() {
        return "license";
    }

    public String getPrevious() {
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        welcomeTextPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        welcomeTextPane.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        welcomeTextPane.setEditable(false);
        welcomeTextPane.setFocusable(false);
        welcomeTextPane.setMargin(new java.awt.Insets(12, 12, 12, 12));
        add(welcomeTextPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane welcomeTextPane;
    // End of variables declaration//GEN-END:variables
}
