/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is JSwat. The Initial Developer of the Original
 * Software is Nathan L. Fiedler. Portions created by Nathan L. Fiedler
 * are Copyright (C) 2005-2006. All Rights Reserved.
 *
 * Contributor(s): Nathan L. Fiedler.
 *
 * $Id$
 */

package com.bluemarsh.jswat.core;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.event.ListDataListener;

/**
 * Panel for editing the single-stepping exclusions.
 *
 * @author  Nathan Fiedler
 */
public class SteppingExcludesPanel extends JPanel implements ActionListener {
    /** serial version UID */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form SteppingExcludesPanel.
     */
    public SteppingExcludesPanel() {
        initComponents();
        // Set the model to something we can work with.
        excludesList.setModel(new DefaultListModel());
        addButton.addActionListener(this);
        removeButton.addActionListener(this);
    }

    /**
     * Invoked when an action occurs.
     *
     * @param  event  action event.
     */
    public void actionPerformed(ActionEvent event) {
        Object src = event.getSource();
        if (src == addButton) {
            String excl = addTextField.getText();
            if (excl.length() > 0) {
                DefaultListModel model = (DefaultListModel) excludesList.getModel();
                model.addElement(excl);
                addTextField.setText("");
            }
        } else if (src == removeButton) {
            DefaultListModel model = (DefaultListModel) excludesList.getModel();
            int[] selections = excludesList.getSelectedIndices();
            for (int ii = selections.length - 1; ii >= 0; ii--) {
                model.remove(selections[ii]);
            }
        }
    }

    /**
     * Adds a listener to the list that's notified each time a change to
     * the data model occurs.
     *
     * @param  l  list data listener to add.
     */
    public void addListDataListener(ListDataListener l) {
        excludesList.getModel().addListDataListener(l);
    }

    /**
     * Get the edited list of single-stepping exclusions.
     *
     * @return  list of single-stepping exclusions.
     */
    public List<String> getValues() {
        DefaultListModel model = (DefaultListModel) excludesList.getModel();
        Enumeration enmr = model.elements();
        List<String> list = new ArrayList<String>(model.getSize());
        while (enmr.hasMoreElements()) {
            String excl = (String) enmr.nextElement();
            list.add(excl);
        }
        return list;
    }

    /**
     * Set the list of single-stepping exclusions to be edited.
     *
     * @param  excludes  list of single-stepping exclusions.
     */
    public void setValues(Object excludes) {
        if (excludes == null) {
            excludes = Collections.emptyList();
        }
        DefaultListModel model = (DefaultListModel) excludesList.getModel();
        model.clear();
        if (excludes instanceof List) {
            List exclList = (List) excludes;
            Iterator iter = exclList.iterator();
            while (iter.hasNext()) {
                String excl = (String) iter.next();
                model.addElement(excl);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        addLabel = new javax.swing.JLabel();
        addTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        excludesScrollPane = new javax.swing.JScrollPane();
        excludesList = new javax.swing.JList();
        removeButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        addLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("KEY_Excludes_AddLabel").charAt(0));
        addLabel.setLabelFor(addTextField);
        addLabel.setText(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("LBL_Excludes_AddLabel"));

        addTextField.setColumns(10);
        addTextField.setToolTipText(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("HINT_Excludes_AddField"));

        addButton.setMnemonic(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("KEY_Excludes_Add").charAt(0));
        addButton.setText(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("LBL_Excludes_Add"));

        excludesScrollPane.setViewportView(excludesList);

        removeButton.setMnemonic(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("KEY_Excludes_Remove").charAt(0));
        removeButton.setText(java.util.ResourceBundle.getBundle("com/bluemarsh/jswat/core/Form").getString("LBL_Excludes_Remove"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addComponent(excludesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLabel)
                    .addComponent(addButton)
                    .addComponent(addTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excludesScrollPane)
                    .addComponent(removeButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addTextField;
    private javax.swing.JList excludesList;
    private javax.swing.JScrollPane excludesScrollPane;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
    
}
