#!/bin/sh
# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# The Original Software is the JSwat launcher. The Initial Developer of the
# Software is Nathan L. Fiedler. Portions created by Nathan L. Fiedler
# are Copyright (C) 2005. All Rights Reserved.
#
# Contributor(s): Nathan L. Fiedler.
#
# $Id: jpdalaunch 2692 2006-12-24 10:40:51Z nfiedler $
#

#
# This script is to be used as the argument for the 'launch' sub-option
# in the JPDA connector arguments. For example:
#
# -agentlib:jdwp=transport=dt_socket,server=y,launch=/bin/jpdalaunch
#
# See the JPDA Connection and Invocation Details for more information.
#

# Determine our path.
PRG=$0
while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
	PRG="$link"
    else
	PRG="`dirname "$PRG"`/$link"
    fi
done
progdir=`dirname "$PRG"`

# Argument 1 is the transport (e.g. dt_socket)
# Argument 2 is the address (e.g. localhost:5000)

$progdir/jswat -J-Djswat.transport=$1 -J-Djswat.address=$2
