#!/bin/sh
#                 Sun Public License Notice
#
# The contents of this file are subject to the Sun Public License
# Version 1.0 (the "License"). You may not use this file except in
# compliance with the License. A copy of the License is available at
# http://www.sun.com/
#
# The Original Code is NetBeans. The Initial Developer of the Original
# Code is Sun Microsystems, Inc. Portions Copyright 1997-2004 Sun
# Microsystems, Inc. All Rights Reserved.
#
# $Id: jswat 2714 2007-01-04 09:41:23Z nfiedler $
#

#
# resolve symlinks
#

PRG=$0

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
	PRG="$link"
    else
	PRG="`dirname "$PRG"`/$link"
    fi
done

progdir=`dirname "$PRG"`

# Rather than etc/jswat.conf, get the Unix version of the file.
if [ -f "$progdir"/../etc/jswat.conf ] ; then
    . "$progdir"/../etc/jswat.conf
fi

if [ -f /etc/jswat.conf ] ; then
    . /etc/jswat.conf
fi

args="$@"

userdir=${netbeans_default_userdir}
while [ $# -gt 0 ] ; do
    case "$1" in
        --userdir) shift; if [ $# -gt 0 ] ; then userdir=$1; fi
            ;;
    esac
    shift
done

if [ -f "${userdir}"/etc/jswat.conf ] ; then
    . "${userdir}"/etc/jswat.conf
fi

netbeans_clusters=""
for i in jswat3 ide7 extra ; do
    if [ -d "$progdir/../$i" ] ; then
        netbeans_clusters="$netbeans_clusters:$progdir/../$i"
    fi
done

if [ ! -z "$netbeans_extraclusters" ] ; then
    netbeans_clusters="$netbeans_clusters:$netbeans_extraclusters"
fi

nbexec="$progdir"/../platform6/lib/nbexec

case "`uname`" in
    Darwin*)
        "$nbexec" \
            --jdkhome "$netbeans_jdkhome" \
            -J-Dcom.apple.mrj.application.apple.menu.about.name=JSwat \
            -J-Xdock:name=JSwat \
            "-J-Xdock:icon=$progdir/../nb4.1/netbeans.icns" \
            --branding jswat \
            --clusters "$netbeans_clusters" \
            --userdir "${userdir}" \
            ${netbeans_default_options} \
            $args
        ;;
    *)
        "$nbexec" \
            --jdkhome "$netbeans_jdkhome" \
            --branding jswat \
            --clusters "$netbeans_clusters" \
            --userdir "${userdir}" \
            ${netbeans_default_options} \
            $args
        ;;
esac
